name: Build
on:
  push:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and test"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test --stacktrace
      - name: Extract version from Gradle
        id: extract_version
        run: |
          VERSION=$(./gradlew :properties -q | grep "^mod.version:" | awk '{print $2}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Find and rename JAR
        run: |
          JAR_FILE=$(find versions/1.21.10-fabric/build/libs/ -name "*.jar" -not -name "*-dev.jar" -not -name "*-sources.jar")
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV
          mv $JAR_FILE versions/1.21.10-fabric/build/libs/SecretRoutes-${{ env.VERSION }}-DEV.jar
      - uses: actions/upload-artifact@v4
        name: Upload SRM
        with:
          name: "SecretRoutes-${{ env.VERSION }}-DEV"
          path: versions/1.21.10-fabric/build/libs/SecretRoutes-${{ env.VERSION }}-DEV.jar
